packages:
  - 'docs'
  - 'examples/*'

minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustLockfile: false
blockExoticSubdeps: true

strictDepBuilds: true
strictPeerDependencies: true
verifyDepsBeforeRun: install

update:
  githubActions: true
patchedDependencies:
  vitepress@2.0.0-alpha.19: patches/vitepress@2.0.0-alpha.19.patch
